# Site settings
title: Chris Laverdiere
email: cmlaverdiere@gmail.com
description: Ay carumba!
baseurl: ""
url: "http://cmlaverdiere.net" # the base hostname & protocol for your site
github_username: cmlaverdiere

# Build settings
markdown: kramdown
